version: "3.8"
services:
  maishatu:
    build:
      context: /home/paulg/dev/services/website/self-host
      dockerfile: /home/paulg/dev/services/website/self-host/Dockerfile
    restart: always
    environment:
      - BUILD_VERSION=${BUILD_VERSION}

  caddy:
    image: caddy:latest
    restart: unless-stopped
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/etc/ssl/certs/custom
      - ./private:/etc/ssl/private/custom
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    depends_on:
      - maishatu

volumes:
  caddy_data:
  caddy_config:
  pnpm-store:
