version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - BUILD_VERSION=${BUILD_VERSION}
    volumes:
      - type: bind
        source: ${PWD}/database.db
        target: /app/database.db
    # networks:
    #   - caddy_network

  caddy:
    image: caddy:latest
    restart: unless-stopped
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/etc/ssl/certs/custom
      - ./private:/etc/ssl/private/custom
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    networks:
      - caddy_network
    depends_on:
      - knowlesglass
      - webdevcody
      - icongeneratorai

  # postgres:
  #   image: postgres
  #   environment:
  #     POSTGRES_DB: voidpulse
  #     POSTGRES_USER: youruser
  #     POSTGRES_PASSWORD: yourpassword
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data

volumes:
  # postgres-data:
  caddy_data:
  caddy_config:
# In case of multiple containers
# networks:
#   caddy_network:
