
services:
    caddy:
        image: caddy:latest
        restart: unless-stopped
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - caddy_data:/data
            - caddy_config:/config
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
volumes:
    caddy_data:
    caddy_config:
